---
title: "2018 End of Season Report"
author: "Sara Tremblay-Boyer"
date: "9 août 2018"
output: github_document
---

```{r setup, include=FALSE}

library(lubridate)
library(tidyverse)
library(googlesheets)
library(here)
library(knitr)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
```

#Loading data: 

```{r import data}
field_data_workbook_2018 <- gs_key("1iRQCKMTznHbMeI9GunbsgPyb-rtWgwj-0IfxLw7NBJE", 
                                   lookup = F, visibility = "private")

surveys <- gs_read(field_data_workbook_2018, ws = "survey_data")
seines <- gs_read(field_data_workbook_2018, ws = "seine_data")
survey_seines_2018 <- full_join(surveys, seines, by = "survey_id")
write_csv(survey_seines_2018, here("Internal Reports", "End of Field Season Reports", "Raw Data", "survey_seines_2018.csv"))
survey_seines_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "Raw Data", "survey_seines_2018.csv"))
  
packages_2018 <- gs_read(field_data_workbook_2018, ws = "package_data")
write_csv(packages_2018, here("Internal Reports", "End of Field Season Reports", "Raw Data", "packages.csv"))
packages_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "Raw Data", "packages.csv"))

fish_2018 <- gs_read(field_data_workbook_2018, ws = "fish_and_sealice_field_data")
fish_2018 <- fish_2018[c(1:9,37)]
write_csv(fish_2018, here("Internal Reports", "End of Field Season Reports", "Raw Data", "fish_2018.csv"))
fish_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "Raw Data", "fish_2018.csv"))

sealice_field_2018 <- gs_read(field_data_workbook_2018, ws = "fish_and_sealice_field_data")
sealice_field_2018 <- sealice_field_2018[c(1:3,10:34,37)]
write_csv(sealice_field_2018, here("Internal Reports", "End of Field Season Reports", "Raw Data", "sealice_field_2018.csv"))
sealice_field_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "Raw Data", "sealice_field_2018.csv"))

```

# Catch Statistics: 
```{r}
#table of the species summary
field_2018_sites_spp_summary <- survey_seines_2018 %>%
  select(survey_date, site_id, so_taken, pi_taken, cu_taken, co_taken, he_taken, ck_taken, region, zone) %>%
   rename(chinook = ck_taken,
         coho = co_taken,
         chum = cu_taken,
         herring = he_taken,
         pink = pi_taken,
         sockeye = so_taken) %>% 
  gather(sockeye, pink, chum, coho, chinook, herring, key = "species", value = "n") %>% 
  replace_na(list( n = 0)) %>% na.omit()

species_summary <- field_2018_sites_spp_summary %>%
  group_by(species) %>% 
  summarize(n = sum(n)) %>% 
  rename(total = n) %>% 
  arrange(desc(total))

knitr::kable(species_summary)

# ording the facets in the right order
field_2018_sites_spp_summary$species <-
  factor(field_2018_sites_spp_summary$species, levels = c("sockeye", "chum", "pink", "coho", "chinook", "herring"))

#making the graph of fish caught for each species in each zone
#TO FIX: etting rid of the double seines 

d <- ggplot(field_2018_sites_spp_summary, aes(x = survey_date, y = zone), group = species) +
  geom_count(aes( size = n, alpha = n)) +
  facet_wrap(~species) +
  scale_y_discrete(limits= c("N", "S", "W","C", "E"),
    breaks= c("W", "S", "N", "E", "C"), 
    labels= c("West", "South", "North", "East", "Central")) +
  labs(x = NULL, y = NULL) +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.ticks.y = element_blank(), axis.text = element_text(color = "gray56"), axis.ticks.x = element_line(color = "gray56")) + scale_size_continuous(range = c(0.5,3.5))
d
ggsave("species_distribution.png", d)  
# looking at the distribution of sockeye retained by each migration zone. Discovery Island versus. Johnstone Strait

sockeye_distribution <- survey_seines_2018 %>%
   select(survey_date, region, zone, so_taken) %>%
  arrange(region, zone) %>%
  rename(sockeye = so_taken) %>% 
  na.omit()

# TO FIX: add May ?

s_colors <- brewer.pal(n = 3, name = "Dark2")
s <- ggplot(sockeye_distribution, aes(x = survey_date, y = zone, color = region)) + geom_count(aes( size = sockeye)) +
  labs(x = NULL, y = NULL)+
  scale_color_manual(values = s_colors,
                     name = "",
                     breaks= c("DI", "JS"),
labels=c("Discovery Islands", "Jonhstone Strait")) +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.ticks.y = element_blank(), axis.text = element_text(color = "gray56"), axis.ticks.x = element_line(color = "gray56")) +
  scale_y_discrete(limits= c("N", "S", "W","C", "E"),
    breaks= c("W", "S", "N", "E", "C"),
                   labels= c("West", "South", "North", "East", "Central"))
s

ggsave("sockeye_distribution.png", s)
```