---
title: "Juvenile Salmon Report"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "About", href: "https://example.com/about", align: left }
    social: menu
    theme : readable
    logo: Hakai_red.png
    favicon: Hakai_red.png
runtime: shiny
---

Analysis {.storyboard}
=========================================

### Frame 1

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```


```{r}
```

### Frame 2

```{r}
```

Another {.storyboard}
=========================================

### Frame 1
```{r}

```

Details
=========================================

Column
-----------------------------------------
