---
title: "2018 End of Season Report"
author: "Julian Gan, Brett Johnson, and Sara Tremblay-Boyer"
date: "11 September 2018"
output: github_document
---

```{r setup, include=FALSE}

library(lubridate)
library(dplyr)
library(tidyverse)
library(googlesheets)
library(here)
library(knitr)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data}
db <- gs_key("1hTC60Nc60k23rMMzcV9clPo4mcR1iqQYgKR2zD6nOfQ", 
                                   lookup = F, visibility = "private")

surveys <- gs_read(db, ws = "survey_data")
seines <- gs_read(db, ws = "seine_data")
survey_seines_2018 <- full_join(surveys, seines, by = "survey_id") %>% 
  filter(survey_date >= as.Date("2018-05-01"))
write_csv(survey_seines_2018, here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "survey_seines_2018.csv"))
survey_seines_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "survey_seines_2018.csv"))
  
packages <- gs_read(db, ws = "package_data")
packages_2018 <- left_join(packages, survey_seines_2018, by = "seine_id") %>% 
  filter(survey_date >= as.Date("2018-05-01")) 
packages_2018 <- packages_2018[c(1:14)]
write_csv(packages_2018, here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "packages.csv"))
packages_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "packages.csv"))

fish <- gs_read(db, ws = "fish_field_data")
fish_2018 <- left_join(fish,survey_seines_2018) %>% 
  filter(survey_date >= as.Date("2018-05-01"))
fish_2018 <- fish_2018[c(2:14,16:18)]
write_csv(fish_2018, here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "fish_2018.csv"))
fish_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "fish_2018.csv"))

sealice_field <- gs_read(db, ws = "sealice_field")
sealice_field_2018 <- left_join(fish_2018,sealice_field, by = "ufn")
write_csv(sealice_field_2018, here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "sealice_field_2018.csv"))
sealice_field_2018 <- read_csv(here("Internal Reports", "End of Field Season Reports", "2018", "Raw Data", "sealice_field_2018.csv"))
```

```{r Ordered logistic regression model to compare sliding activity vs. sockeye catch}
library(MASS)
library(reshape2)

sreg <- survey_seines_2018 %>% 
  dplyr::select(set_sliders, so_total, cu_total, pi_total)

sreg$set_sliders <- as.factor(sreg$set_sliders)
slider <- sreg$set_sliders
sototal <- sreg$so_total

### Perforoming Ordered Logisitic Regression on slider activity and total sockeye catch.
slider_so_logit <- polr(slider ~ sototal, data = sreg, Hess = T)
summary (slider_so_logit)
oddsratio <- exp(coef(slider_so_logit)) #coeffecients are log odds so I exponentitate them (with base e) to get odds ratio 
oddsratio
##storing table
(slider_so_table <- coef(summary(slider_so_logit)))
slider_so_p <- pnorm(abs(slider_so_table[,"t value"]), lower.tail = FALSE) * 2
(slider_so_table <- cbind(slider_so_table, "p value" = slider_so_p))
(slider_so_ci <- confint(slider_so_logit))
exp(cbind(OR = coef(slider_so_logit), slider_so_ci))

detach("package:MASS", unload = TRUE)
```

```{r time each of the first ten sockeye are out of the water}
sea_lice_duration_out <- sealice_field_2018 %>% 
  filter(licing_protocol_field == "salmoncoast_allstages") %>% 
  select(ufn, region, fish_time_out, fish_time_dewar) %>% 
  mutate(duration_out = (fish_time_dewar - fish_time_out)/60)

(mean(sea_lice_duration_out$duration_out))
ggplot(sea_lice_duration_out, aes(x = duration_out)) +
  geom_histogram(binwidth = 2)+
  xlim(2,25) +
  xlab("Duration Out (minutes)")+
  ylab("Count")

ggsave(here("Internal Reports", "End of Field Season Reports", "2018", "Figures", "sealice_field_2018.png"), width = 5, height = 3)
```

```{r fish loused in 2018 vs. 2017}
library(ggplot2)
library(wesanderson)

survey_seines <- full_join(surveys,seines, by = "survey_id")
fish_survey_seines <- left_join(fish,survey_seines)
all_fish_lice <- full_join(fish_survey_seines, sealice_field, by = "ufn") %>% 
  filter(licing_protocol_field != "NA") %>% 
  filter(species == "SO" | species == "PI" | species=="CU") %>% 
  mutate(survey_year = as.character(year(survey_date))) %>% 
  select(ufn,species,region,survey_year) %>% 
  group_by(species,survey_year)

summarise(all_fish_lice, count=n())

ggplot(data = all_fish_lice) + 
  geom_bar(mapping = aes(x=species, fill=survey_year), position=position_dodge()) + 
  scale_fill_manual(name="Survey Year", values = wes_palette("Zissou1")) +
  xlab("Species") +
  ylab("Count")
ggsave(here("Internal Reports", "End of Field Season Reports", "2018", "Figures", "comparison_fish_loused_2017-18.png"), width = 5, height = 3)
```

```{r Catch Statistics}
# Summary table of number of each species retained
field_2018_sites_spp_summary <- survey_seines_2018 %>%
  select(survey_date, site_id, so_taken, pi_taken, cu_taken, co_taken, he_taken, ck_taken, region, zone) %>%
   rename(chinook = ck_taken,
         coho = co_taken,
         chum = cu_taken,
         herring = he_taken,
         pink = pi_taken,
         sockeye = so_taken) %>% 
  gather(sockeye, pink, chum, coho, chinook, herring, key = "species", value = "n") %>% 
  replace_na(list( n = 0)) %>% na.omit()

species_summary <- field_2018_sites_spp_summary %>%
  group_by(species) %>% 
  summarize(n = sum(n)) %>% 
  rename(total = n) %>% 
  arrange(desc(total))

knitr::kable(species_summary)

# Properly ordering the facets
field_2018_sites_spp_summary$species <-
  factor(field_2018_sites_spp_summary$species, levels = c("sockeye", "chum", "pink", "coho", "chinook", "herring"))

#making the graph of nbr of fish caught for each species in each zone
#TO IMPROVE: getting rid of the double seines points

d <- ggplot(field_2018_sites_spp_summary, aes(x = survey_date, y = zone), group = species) +
  geom_count(aes( size = n, alpha = n)) +
  facet_wrap(~species) +
  scale_y_discrete(limits= c("N", "S", "W","C", "E"),
    breaks= c("W", "S", "N", "E", "C"), 
    labels= c("West", "South", "North", "East", "Central")) +
  labs(x = NULL, y = NULL) +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.ticks.y = element_blank(), axis.text = element_text(color = "gray56"), axis.ticks.x = element_line(color = "gray56")) + scale_size_continuous(range = c(0.5,3.5))
d
ggsave("species_distribution.png", d)  
# looking at the distribution of sockeye retained by each migration zone. Discovery Island versus. Johnstone Strait

sockeye_distribution <- survey_seines_2018 %>%
   select(survey_date, region, zone, so_taken) %>%
  arrange(region, zone) %>%
  rename(sockeye = so_taken) %>% 
  na.omit()

# TO IMPROVE: add May ?

s_colors <- brewer.pal(n = 5, name = "Dark2")
s <- ggplot(sockeye_distribution, aes(x = survey_date, y = zone, color = region)) + geom_count(aes( size = sockeye)) +
  labs(x = NULL, y = NULL)+
  scale_color_manual(values = s_colors,
                     name = "",
                     breaks= c("DI", "JS"),
labels=c("Discovery Islands", "Jonhstone Strait")) +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.ticks.y = element_blank(), axis.text = element_text(color = "gray56"), axis.ticks.x = element_line(color = "gray56")) +
  scale_y_discrete(limits= c("N", "S", "W","C", "E"),
    breaks= c("W", "S", "N", "E", "C"),
                   labels= c("West", "South", "North", "East", "Central"))
s

ggsave("sockeye_distribution.png", s)

#FOR FUN... maybe by site_id instead of region 

for_fun <- survey_seines_2018 %>%
select(survey_date, region, zone, site_id, so_taken) %>%
arrange(region, zone, site_id) %>%
rename(sockeye = so_taken) %>% 
  na.omit()

#changing facet labels and order of sites
region_labels <- c(DI = "Discovery Islands", JS = "Johnstone Strait")

for_fun$site_id <- factor(for_fun$site_id, levels = c("J11", "J09", "J03","J02","D10","D30", "D09","D07", "D27", "D22", "D08"))

#The graph 
f <- ggplot(for_fun, aes(x = survey_date, y = site_id, color = zone)) + geom_count(aes( size = sockeye), alpha = 1/ 2) +
labs(x = NULL, y = NULL)+
  scale_color_manual(values = s_colors,
                     name = "Zone",
                     breaks= c("W","C","E","N", "S"),
labels=c("West", "Central", "East", "North", "South")) +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.ticks.y = element_blank(), axis.text = element_text(color = "gray56"), axis.ticks.x = element_line(color = "gray56")) +
   facet_wrap(~region, nrow = 2, scales = "free_y", labeller = labeller( region = region_labels))+
  scale_size_continuous(range = c(1,5))
f

ggsave("site_id_sockeye.png",f)
```