---
title: "Hakai Institute Juvenile Salmon Report"
author: "Brett Johnson"
date: '`r date()`'
output:
 html_document:
   theme: cosmo
   code_folding: show
   toc: true
   toc_float: true
   number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
library(hakaisalmon)
library(tidyverse)
library(lubridate)
library(here)
library(googlesheets)

inventory <- gs_key('1Ti5gGvakA4DUTjCUZ_VYHULU_FJCK05-zdly5E80Tzs', lookup = FALSE, visibility = "private")

dna_metadata <- gs_read(inventory, ws = "dna_metadata")

sampling_wb <- gs_key('11HZKvkmdbG98iEIDRkeFlwZpViLxhZ8NTxIpGqx0cV0', lookup = F,
                      visibility = "private")

sites <- gs_read(sampling_wb, ws = "2015-2018")
```


```{r 2015}
all_gsi_samples_2015 <- survey_seines_fish_stock_id %>% 
  mutate(year = year(survey_date)) %>% 
  filter(year == 2015) %>% 
  group_by(site_id, dissection_status) %>% 
  summarise(n = n()) %>% 
  spread(dissection_status, n)

results_gsi_samples_2015 <- survey_seines_fish_stock_id %>% 
  mutate(year = year(survey_date)) %>% 
  filter(year == 2015) %>% 
  drop_na(stock_1) %>% 
  group_by(site_id) %>% 
  summarise(results = n())

summary_gsi_2015 <- full_join(all_gsi_samples_2015, results_gsi_samples_2015, by = "site_id") %>% 
  filter(site_id %in% c('J03', 'J05', 'J06', 'J09', 'D09')) %>% 
  mutate(dissected_w_no_results = dissected - results)
  
# Join collection to locations and sample status
samples_2015 <- survey_seines_fish %>% 
  mutate(year = year(survey_date)) %>% 
  filter(year == 2015) %>% 
  filter(site_id %in% c('J03', 'D09'), dissection_status == "dissected") %>% 
  left_join(dna_metadata, by = c("ufn")) %>% 
  left_join(sample_container_inventory) %>% 
  select(ufn, survey_date, lat, lon, semsp_id, sample_id, site_id, species, dissection_status, current_location, sample_status, container_id, sample_id, sample_location) %>% 
  filter(sample_status == "collected")

ggplot(samples_2015, aes(x = survey_date, colour = species)) +
  geom_histogram()
```


```{r 2018 submission: 2018 SO plus all CK and CO}
gsi_SO_2018 <- survey_seines_fish %>% 
  filter(year(survey_date) == 2018, species == "SO") %>% 
  nrow()

CK_CO_not_dissected <- survey_seines_fish %>% 
  filter(species %in% c('CK', 'CO')) %>% 
  left_join(dna_metadata) %>% 
  left_join(sample_container_inventory) %>% 
  filter(dissection_status == "not dissected") %>% 
  select(ufn, survey_date, semsp_id, sample_id, site_id, species, dissection_status, current_location, sample_status, container_id, sample_id, sample_location)

CK_CO <- survey_seines_fish %>% 
  filter(species %in% c('CK', 'CO')) %>% 
  nrow() 

SO_CK_CO <- CK_CO + gsi_SO_2018

SO_2015 <- nrow(samples_2015)

total_for_2018_submission <- SO_CK_CO + SO_2015
```

```{r chinook and coho locations}
ck_samples <- survey_seines_fish %>% 
  filter(species == "CK") %>% 
  group_by(site_id, species) %>% 
  summarise(n = n()) %>% 
  left_join(sites, by = "site_id") %>% 
  ungroup()

co_samples <- survey_seines_fish %>% 
  filter(species == "CO") %>% 
  group_by(site_id, species) %>% 
  summarise(n = n()) %>% 
  left_join(sites, by = "site_id") %>% 
  ungroup()
```

```{r make a map}
library(raster)
library(maps) 
library(mapdata)
library(maptools)
library(rgeos)
library(rgdal)
library(ggplot2)
library(ggsn)
library(tidyverse)
library(here)

BC.shp <- readOGR(here("data", "2_Shapefile", "COAST_TEST2.shp"))

quadra <- extent(-127.0, -124.6, 49.9, 50.8)

BC.sh2 <- crop(BC.shp, quadra)

BC.df <- fortify(BC.sh2)

ck_map <- ggplot()+ theme_bw()+
    geom_polygon(data= BC.df, aes(x=long,y=lat,group= group),
      colour= "black", size=0.1, fill='grey95')+
  geom_point(data = ck_samples, aes(x=long, y=lat, colour = species), size=5, stroke=1.5)+  #add this to plot site locations
  scale_shape_manual(values=c(19,20))+      
  scalebar(BC.df, dist = 10, st.size=4, height=0.01, dd2km = TRUE, model = 'WGS84', anchor = c(x = -126.5, y = 50.0))+
  north(data = BC.df, scale = 0.15, symbol = 3, anchor= c(x = -124.6, y = 50.75)) +
    theme(panel.grid.minor = element_line(colour = NA),
          panel.grid.major = element_line(colour = NA),
          axis.title.y= element_blank(), axis.title.x = element_blank(),
          axis.text.y= element_text(size=10), axis.text.x = element_text(size=10))+
    scale_x_continuous(limits = c(-127.0,-124.6), expand = c(0,0)) +
    scale_y_continuous(limits = c(49.9, 50.8), expand = expand_scale(mult = c(0, 0))) +
    geom_text(data = ck_samples, aes(x = long, y = lat, label=n),
              hjust=.4, vjust=0.25, colour = "black", size = 4) +
  geom_text(aes(x = -126.25, y = 50.2, label = "Northern Vancouver Island")) +
  geom_text(aes(x = -125.25, y = 50.2, label = "Quadra")) +
  ggtitle("Juvenile Chinook Capture Locations 2015 -- 2018")
  
  

ck_map  
ggsave(here("figs", "hakai_chinook_map.png"))

co_map <- ggplot()+ theme_bw()+
    geom_polygon(data= BC.df, aes(x=long,y=lat,group= group),
      colour= "black", size=0.1, fill='grey95')+
  geom_point(data = co_samples, aes(x=long, y=lat, colour = species), size=4, stroke=1.5)+  #add this to plot site locations
  scale_shape_manual(values=c(19))+      
  scalebar(BC.df, dist = 10, st.size=4, height=0.01, dd2km = TRUE, model = 'WGS84', anchor = c(x = -126.5, y = 50.0))+
  north(data = BC.df, scale = 0.15, symbol = 3, anchor= c(x = -124.6, y = 50.75)) +
    theme(panel.grid.minor = element_line(colour = NA),
          panel.grid.major = element_line(colour = NA),
          axis.title.y= element_blank(), axis.title.x = element_blank(),
          axis.text.y= element_text(size=10), axis.text.x = element_text(size=10))+
    scale_x_continuous(limits = c(-127.0,-124.6), expand = c(0,0)) +
    scale_y_continuous(limits = c(49.9, 50.8), expand = expand_scale(mult = c(0, 0))) +
    geom_text(data = co_samples, aes(x = long, y = lat, label=n),
              hjust=.4, vjust=.25, colour = "black", size = 4) +
  geom_text(aes(x = -126.25, y = 50.2, label = "Northern Vancouver Island")) +
  geom_text(aes(x = -125.25, y = 50.2, label = "Quadra")) +
  ggtitle("Juvenile Coho Capture Locations 2015 -- 2018")
  
co_map
ggsave(here("figs", "hakai_coho_map.png"))
```

